<?php
/**
 * @file
 * Provides primary Backdrop hook implementations.
 */

/**
 * Implements hook_permission().
 */
function project_maker_permission() {
  return array(
    'administer project maker' => array(
      'title' => t('Administer Project maker'),
      'description' => t('Administer Project maker.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function project_maker_menu() {
  $items['admin/config/development/project-maker'] = array(
    'title' => 'Create module',
    'description' => 'Create module.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('project_maker_create_module_form'),
    'access arguments' => array('administer project maker'),
  );
  $items['admin/config/development/project-maker/module'] = array(
    'title' => 'Create module',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/config/development/project-maker/theme'] = array(
    'title' => 'Create theme',
    'description' => 'Create project.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('project_maker_create_theme_form'),
    'access arguments' => array('administer project maker'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/config/development/project-maker/layout'] = array(
    'title' => 'Create layout',
    'description' => 'Create project.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('project_maker_create_layout_form'),
    'access arguments' => array('administer project maker'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Form builder for the project maker creation form.
 */
function project_maker_create_module_form($form, &$form_state, $theme = NULL) {
  $form['#tree'] = FALSE;

  $form['intro'] = array(
    '#type' => 'help',
    '#markup' => t('This form automates the initial creation of a module package. A new folder will be created in your modules directory, with all the necessary files (according to selected options below). For more information, see the documentation on <a href="@link">creating a module</a>.', array('@link' => url('https://docs.backdropcms.org/creating-modules'))),
  );

  $form['type'] = array(
    '#type' => 'value',
    '#value' => 'module',
  );
  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Module name'),
    '#maxlength' => 64,
    '#description' => t('Human-readable module name.'),
    '#required' => TRUE,
    '#id' => 'module-name',
  );
  $form['project_name'] = array(
    '#type' => 'machine_name',
    '#maxlength' => 128,
    '#machine_name' => array(
      'exists' => 'project_maker_project_exists',
      'source' => array('name'),
    ),
    '#description' => t('Module machine name'),
  );
  $form['project_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Project description'),
    '#description' => t('Project description.'),
    '#required' => TRUE,
  );
  $form['base_theme_wrapper']['include_common_hooks'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Implement Hooks'),
    '#options' => array(
      'hook_menu' => t('hook_menu()'),
      'hook_permission' => t('hook_permission()'),
      // 'hook_theme' => t('hook_theme()'),
      // 'hook_autoload_info' => t('hook_autoload_info()'),
      // 'hook_config_info' => t('hook_config_info()'),
      // 'hook_admin_paths' => t('hook_admin_paths()'),
      // 'hook_block_configure' => t('hook_block_configure()'),
      // 'hook_block_info' => t('hook_block_info()'),
      // 'hook_block_save' => t('hook_block_save()'),
      // 'hook_block_view' => t('hook_block_view()'),
      // 'hook_cron' => t('hook_cron()'),
      // 'hook_entity_info' => t('hook_entity_info()'),
      // 'hook_form_FORM_ID_alter' => t('hook_form_FORM_ID_alter()'),
      // 'hook_form_alter' => t('hook_form_alter()'),
      // 'hook_library_info' => t('hook_library_info()'),
    ),
    '#description' => t('Choose additional module files to be created.'),
  );

  $form['base_theme_wrapper']['include_options'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Create additional files and folders'),
    '#options' => array(
      'install' => t('Install file'),
      'admin' => t('Admin file'),
      'theme' => t('Theme file'),
      // 'config' => t('Config file'),
      'theme' => t('Theme file'),
      'js' => t('Javascript (js) file'),
      'css' => t('CSS file'),
      // 'test' => t('Test file'),
    ),
    '#description' => t('Choose additional module files to be created.'),
  );
  $form['base_theme_wrapper']['include_install_hooks'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Implement Hooks in Install file'),
    '#options' => array(
      'hook_enable' => t('hook_enable()'),
      // 'hook_disable' => t('hook_disable()'),
      // 'hook_install' => t('hook_install()'),
      // 'hook_schema' => t('hook_schema()'),
      // 'hook_uninstall' => t('hook_uninstall()'),
    ),
    '#description' => t('Choose additional module files to be created.'),
  );


  $form['custom_functions'] = array(
    '#type' => 'textarea',
    '#title' => t('Create custom functions'),
    '#description' => t('Enter custom function names, one per line. Module name will be prefixed automatically. For example <em>create_widget</em>  will be converted to <em>MODULE_NAME_create_widget</em>.'),
    '#rows' => 3,
    '#default_value' => '',
  );

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['create_module'] = array(
    '#type' => 'submit',
    '#validate' => array('project_maker_create_module_form_validate'),
    '#submit' => array('project_maker_create_project_form_submit'),
    '#value' => t('Create module'),
  );

  return $form;
}

/**
 * Form builder for the project maker creation form.
 */
function project_maker_create_theme_form($form, &$form_state, $theme = NULL) {
  $form['#tree'] = FALSE;
  $themes = system_rebuild_theme_data();
  $page_title = t('Create theme');
  $hide_theme_selection = FALSE;

  $options = array();
  $options['new'] = t('No base theme');
  foreach ($themes as $theme_name => $theme_info) {
    $options[$theme_name] = $theme_info->info['name'];
  }

  $form_state['theme_name'] = 'new';
  if (isset($form_state['values']['base_theme'])) {
    $form_state['theme_name'] = $form_state['values']['base_theme'];
  }
  elseif ($theme) {
    $form_state['theme_name'] = $theme;
    $page_title = t('Create subtheme from @theme', array('@theme' => $options[$theme]));
    $hide_theme_selection = TRUE;
  }
  $form_state['themes'] = $themes;

  
  $selected_theme_name_string = '';
  if ($form_state['theme_name']!= 'new') {
    $form_state['theme_name'] = $form_state['values']['base_theme'];
    $selected_theme = $themes[$form_state['theme_name']];
    $selected_theme_name = $selected_theme->info['name'];
    $selected_theme_name_string = t(' from @selected_theme_name', array('@selected_theme_name' => $selected_theme_name));
  }

  backdrop_set_title($page_title);

  $form['type'] = array(
    '#type' => 'value',
    '#value' => 'theme',
  );

  $form['intro'] = array(
    '#type' => 'help',
    '#markup' => t('This form automates the initial creation of a subtheme. A new folder will be created in your themes directory, with all the necessary files (according to selected options below). For more information, see the documentation on <a href="@link">creating a subtheme</a>.', array('@link' => url('https://docs.backdropcms.org/documentation/creating-sub-themes'))),
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Theme name'),
    '#maxlength' => 64,
    '#description' => t('Human-readable subtheme name.'),
    '#required' => TRUE,
    '#id' => 'subtheme-name',
  );
  $form['project_name'] = array(
    '#type' => 'machine_name',
    '#maxlength' => 128,
    '#machine_name' => array(
      'exists' => 'project_maker_project_exists',
      'source' => array('name'),
    ),
    '#description' => t('Subtheme machine name'),
  );
  $form['project_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Project description'),
    '#description' => t('Project description.'),
    '#required' => TRUE,
  );
  if ($hide_theme_selection) {
    $form['base_theme'] = array(
      '#type' => 'hidden',
      '#value' => $form_state['theme_name'],
    );
  }
  else {
    $form['base_theme'] = array(
      '#type' => 'select',
      '#title' => t('Base theme'),
      '#options' => $options,
      '#parents' => array('base_theme'),
      '#default_value' => $form_state['theme_name'],
      '#ajax' => array(
        'callback' => 'base_theme_wrapper_change_callback',
        'wrapper' => 'base_theme_wrapper',
        'event' => 'change',
        'method' => 'replace',
        'effect' => 'fade',
      ),
    );
  }
  $form['base_theme_wrapper'] = array(
    '#type' => 'container',
    '#id' => 'base_theme_wrapper',
   // '#access' => $form_state['theme_name'],
    '#attributes' => array(
      'class' => array('base-theme-wrapper clearfix'),
    ),
  );
  if ($form_state['theme_name'] !== 'new' && theme_has_color_support($form_state['theme_name'])) {
    $form['base_theme_wrapper']['copy_color'] = array(
    '#type' => 'checkbox',
    '#title' => t('Copy color settings') . $selected_theme_name_string,
    '#description' => t('Include this if you plan to modify the color module settings.'),
    );
  }
  if (!empty($themes[$form_state['theme_name']]->info['settings'])) {
    $form['base_theme_wrapper']['copy_settings'] = array(
    '#type' => 'checkbox',
    '#parent' => 'settings',
    '#title' => t('Copy theme settings') . $selected_theme_name_string,
    );
  }

  $template_list = project_maker_theme_templates($form_state['theme_name']);

  if (!empty($template_list)) {
    $form['base_theme_wrapper']['template_list'] = array(
      '#type' => 'checkboxes',
      '#options' => $template_list,
      '#title' => t('Copy template files') . $selected_theme_name_string,
      '#parent' => 'template_list',
      '#description' => t('Now is a good time to add any template files you know you will be editing, or you can add them manually later.'),
    );
  }

  if ($form_state['theme_name'] === 'new') {
    $form['base_theme_wrapper']['template_files'] = array(
      '#type' => 'checkboxes',
      '#options' => array(
        'node' => t('node.tpl.php'),
        'comment' => t('comment.tpl.php'),
        'header' => t('header.tpl.php'),
        'maintenance-page' => t('maintenance-page.tpl.php'),
      ),
      '#title' => t('Create template files'),
      '#parent' => 'template_list',
      '#description' => t('Select template files to create now, or you can add them manually later.'),
    );
    $form['base_theme_wrapper']['copy_theme_settings_php'] = array(
      '#type' => 'checkbox',
      '#title' => t('Create blank theme-settings.php'),
      '#description' => t('Useful if you plan to include any custom settings for your theme.'),
    );
  }
  $form['copy_template_php'] = array(
    '#type' => 'checkbox',
    '#title' => t('Create blank template.php'),
    '#parent' => 'copy_template_php',
    '#description' => t('Useful if you plan to include any custom php in your theme.'),
  );
  $form['styles'] = array(
    '#type' => 'textarea',
    '#title' => t('Add stylesheet paths'),
    '#description' => t('Enter relative paths, one per line. A blank CSS file will be created at this path. For example <em>css/custom.css</em> (file placed in a "css" folder) or <em>style.css</em> (file placed in root).'),
    '#rows' => 3,
    '#default_value' => 'css/custom.css',
  );
  $form['scripts'] = array(
    '#type' => 'textarea',
    '#title' => t('Add script paths'),
    '#description' => t('Enter relative paths, one per line. A blank JS file will be created at this path. For example <em>js/scripts.js</em> (file placed in a "js" folder) or <em>js-scripts.js</em> (file placed in root).'),
    '#rows' => 3,
  );
  $form['actions'] = array('#type' => 'actions');
  $form['actions']['create_subtheme'] = array(
    '#type' => 'submit',
    '#validate' => array('project_maker_create_theme_form_validate'),
    '#submit' => array('project_maker_create_project_form_submit'),
    '#value' => t('Create subtheme'),
  );

  return $form;
}

/**
 * Form builder for the project maker creation form.
 */
function project_maker_create_layout_form($form, &$form_state, $theme = NULL) {

  $form['type'] = array(
    '#type' => 'value',
    '#value' => 'layout',
  );

  $form['intro'] = array(
    '#type' => 'help',
    '#markup' => t('This form automates the initial creation of a layout template package. A new folder will be created in your layouts directory, with all the necessary files (according to selected options below). For more information, see the documentation on <a href="@link">creating a subtheme</a>.', array('@link' => url('https://docs.backdropcms.org/documentation/creating-sub-themes'))),
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('Layout name'),
    '#maxlength' => 64,
    '#description' => t('Human-readable layout name.'),
    '#required' => TRUE,
    '#id' => 'layout-name',
  );
  $form['project_name'] = array(
    '#type' => 'machine_name',
    '#maxlength' => 128,
    '#machine_name' => array(
      'exists' => 'project_maker_project_exists',
      'source' => array('name'),
    ),
    '#description' => t('Subtheme machine name'),
  );
  $form['project_description'] = array(
    '#type' => 'textfield',
    '#title' => t('Project description'),
    '#description' => t('Project description.'),
    '#required' => TRUE,
  );


  $templates = layout_get_layout_template_info();
  $template_list = array();
  $template_list['blank'] = t('Blank');
  foreach ($templates as $key => $list) {
    if (empty($list['flexible']) && !$list['hidden'] && !empty($list['template'])) {
      $template_list[$key] = theme('layout_template_info', array('template_info' => $list));
    }
  }

  $form['#attached']['css'][] = backdrop_get_path('module', 'layout') . '/css/layout.admin.css';
  $form['base_theme_wrapper']['template_list'] = array(
    '#type' => 'checkboxes',
    '#options' => $template_list,
    '#title' => t('Copy template files'),
    '#attributes' => array('class' => array('layout-list')),
    '#description' => t('The template (*.tpl.php) files will be copied from the existing layout template selected.'),
  );


  $form['actions'] = array('#type' => 'actions');
  $form['actions']['create_subtheme'] = array(
    '#type' => 'submit',
    '#validate' => array('project_maker_create_layout_form_validate'),
    '#submit' => array('project_maker_create_project_form_submit'),
    '#value' => t('Create layout template'),
  );

  return $form;
}

/**
 * AJAX callback to update the condition settings.
 */
function base_theme_wrapper_change_callback($form, $form_state) {
  return $form['base_theme_wrapper'];
}

function project_maker_theme_templates($theme_name) {
  $dir_path = backdrop_get_path('theme', $theme_name);
  $template_list = array();
  $files = file_scan_directory($dir_path, '/.*tpl\.php/');
  foreach ($files as $file) {
    $template_list[$file->uri] = $file->filename;
  }
  return $template_list;
    
}

function project_maker_project_exists($theme_name) {
  $themes = list_themes();
  return isset($themes[$theme_name]);
}

/**
 * Validation handler for the subtheme creation form.
 */
function project_maker_create_module_form_validate($form, &$form_state) {
  dpm($form_state['values']);
  if ($form_state['values']['include_options']['css']) {
    $form_state['values']['styles'][] = 'css/' . $form_state['values']['project_name'] . '.css';
  }
  if ($form_state['values']['include_options']['js']) {
    $form_state['values']['scripts'][] = 'js/' . $form_state['values']['project_name'] . '.js';
  }
}

/**
 * Validation handler for the subtheme creation form.
 */
function project_maker_create_layout_form_validate($form, &$form_state) {
}

/**
 * Validation handler for the subtheme creation form.
 */
function project_maker_create_theme_form_validate($form, &$form_state) {
  // @Todo: Need sanitizing?
  if (!empty($form_state['values']['styles'])) {
    $styles = explode("\n", $form_state['values']['styles']);
    $styles = array_map('trim', $styles);
    $styles = array_filter($styles, 'strlen');
    foreach ($styles as $key => $style) {
      $pathinfo = pathinfo($style);
      if (valid_url($style) && strpos($pathinfo['dirname'], ".") === false && isset($pathinfo['extension']) && $pathinfo['extension'] == 'css') {
        $styles[$key] = $style;
      }
      else {
        form_set_error('styles', t('One or more of your stylesheet paths is not valid.'));
      }
    }
    $form_state['values']['styles'] = $styles;
  }
  if (!empty($form_state['values']['scripts'])) {
    $scripts = explode("\n", $form_state['values']['scripts']);
    $scripts = array_map('trim', $scripts);
    $scripts = array_filter($scripts, 'strlen');
    foreach ($scripts as $key => $script) {
      $pathinfo = pathinfo($script);
      if (valid_url($script) && strpos($pathinfo['dirname'], ".") === false && isset($pathinfo['extension']) && $pathinfo['extension'] == 'js') {
        $scripts[$key] = $script;
      }
      else {
        form_set_error('scripts', t('One or more of your script paths is not valid.'));
      }
    }
    $form_state['values']['scripts'] = $scripts;
  }
  dpm($form_state['values']);
}

/**
 * Submit handler for the subtheme creation form.
 */
function project_maker_create_project_form_submit($form, &$form_state) {
  $module_name = check_plain($form_state['values']['project_name']);
  $success = project_maker_process_project_directory($form_state, $module_name);
  if ($success) {
    backdrop_set_message(t('Subtheme %subtheme was created successfully.', array('%subtheme' => $form_state['values']['name'])));
    // $form_state['redirect'] = 'admin/appearance';
  }
  else {
    backdrop_set_message(t('Subtheme creation failed to complete.'), 'error');
  }
}

/**
 * Converts files in a theme directory.
 */
function project_maker_process_project_directory($form_state, $project_name) {
  $values = $form_state['values'];
  // $dirname = BACKDROP_ROOT . '/' . backdrop_get_path('theme', $module_name);
  $new_dirname = BACKDROP_ROOT . '/' . $values['type'] . 's/' . check_plain($project_name);

  // Create an output directory we can write to.
  if (!is_dir($new_dirname)) {
    file_prepare_directory($new_dirname, FILE_CREATE_DIRECTORY);
  }
  else {
    backdrop_set_message(t('The subtheme directory already exists.'), 'error');
    return FALSE;
  }

  // Build the info file.
  $values['theme_name'] = $project_name;
  $info_file_array = project_maker_build_info_file_array($values);

  $info_file = project_maker_build_info_file($info_file_array);
  $info_file_path = $new_dirname . '/' . $values['project_name'] . '.info';
  if (file_put_contents($info_file_path, $info_file) === FALSE) {
    backdrop_set_message(t('The info file could not be written.'), 'error');
    backdrop_rmdir($new_dirname);
    return FALSE;
  }

  // Create CSS and JS folders.
  if (!empty($values['styles'])) {
    foreach ($values['styles'] as $style) {
      $pathinfo = pathinfo($style);
      $path = $new_dirname . '/' . $pathinfo['dirname'];
      file_prepare_directory($path, FILE_CREATE_DIRECTORY);
      file_put_contents($new_dirname . '/' . $style, '');
    }
  }
  if (!empty($values['scripts'])) {
    foreach ($values['scripts'] as $script) {
      $pathinfo = pathinfo($script);
      $path = $new_dirname . '/' . $pathinfo['dirname'];
      file_prepare_directory($path, FILE_CREATE_DIRECTORY);
      file_put_contents($new_dirname . '/' . $script, '');
    }
  }

  switch ($values['type']) {
    case 'module':
      $success = project_maker_process_module_data($values, $new_dirname);
      break;

    case 'theme':
      $success = project_maker_process_theme_data($values, $new_dirname);
      break;

    case 'layout':
      $success = project_maker_process_layout_data($values, $new_dirname);
      break;
  }

  return TRUE;

}

/**
 * Converts files in a theme directory.
 */
function project_maker_process_module_data($values, $new_dirname) {
  module_load_include('inc', 'project_maker', 'project_maker_strings');
  $project_name = $values['project_name'];

  // Create a module file.
  $string = project_maker_replacement_strings('module', $values['project_description']);
  if ($values['include_common_hooks']['hook_menu']) {
    $string .= project_maker_replacement_strings('hook_menu', $project_name);
  }
  if ($values['include_common_hooks']['hook_permission']) {
    $string .= project_maker_replacement_strings('hook_permission', $project_name);
  }
  $module_file = $project_name . '.module';
  file_put_contents($new_dirname . '/' . $module_file, $string);

  // Create an install file.
  if ($values['include_options']['install']) {
    $string = project_maker_replacement_strings('install', $project_name);
    if ($values['include_install_hooks']['hook_enable']) {
      $string .= project_maker_replacement_strings('hook_enable', $project_name);
    }
    $install_file = $project_name . '.install';
    file_put_contents($new_dirname . '/' . $install_file, $string);
  }

  // Create an admin.inc file.
  if ($values['include_options']['admin']) {
    $string = project_maker_replacement_strings('admin', $project_name);
    $admin_file = $project_name . '.admin.inc';
    file_put_contents($new_dirname . '/' . $admin_file, $string);
  }

  // Create an theme.inc file.
  if ($values['include_options']['theme']) {
    $string = project_maker_replacement_strings('theme', $project_name);
    $theme_file = $project_name . '.theme.inc';
    file_put_contents($new_dirname . '/' . $theme_file, $string);
  }

  // Create a JS file.
  if ($values['include_options']['js']) {
    $string = project_maker_replacement_strings('js', $project_name);
    $js_file = $project_name . '.js';
    $path = $new_dirname . '/js';
    file_prepare_directory($path, FILE_CREATE_DIRECTORY);
    file_put_contents($path . '/' . $js_file, $string);
  }

  // Create a CSS file.
  if ($values['include_options']['css']) {
    $string = project_maker_replacement_strings('css', $project_name);
    $css_file = $project_name . '.css';
    $path = $new_dirname . '/css';
    file_prepare_directory($path, FILE_CREATE_DIRECTORY);
    file_put_contents($path . '/' . $css_file, $string);
  }
}

/**
 * Converts files in a theme directory.
 */
function project_maker_process_theme_data($values, $new_dirname) {
}

/**
 * Converts files in a theme directory.
 */
function project_maker_process_layout_data($values, $new_dirname) {
}

/**
 * Converts files in a theme directory.
 */
function project_maker_process_theme_directory($form_state) {
  $theme_name = check_plain($form_state['theme_name']);
  $values = $form_state['values'];
  $dirname = BACKDROP_ROOT . '/' . backdrop_get_path('theme', $form_state['theme_name']);
  $new_dirname = BACKDROP_ROOT . '/themes/' . check_plain($values['subtheme_name']);

  // Create an output directory we can write to.
  if (!is_dir($new_dirname)) {
    file_prepare_directory($new_dirname, FILE_CREATE_DIRECTORY);
  }
  else {
    backdrop_set_message(t('The subtheme directory already exists.'), 'error');
    return FALSE;
  }

  // Copy the favicon, logo, theme-settings.php
  $allowed_filenames = array(
    'favicon.ico',
    'logo.png',
  );
  if (!empty($values['copy_settings'])) {
    $allowed_filenames[] = 'theme-settings.php';
  }
    
  foreach ($allowed_filenames as $filename) {
    if (file_exists($dirname . '/' . $filename)) {
      copy($dirname . '/' . $filename, $new_dirname . '/' . $filename);
      project_maker_convert_file($new_dirname . '/' . $filename, $form_state);
    }
  }

  // Create a color directory if needed.
  if (!empty($values['copy_color'])) {
    $copy_color_item = array(
      'old_dir' => $dirname . '/color',
      'new_dir' => $new_dirname . '/color',
    );
    project_maker_copy_dir($copy_color_item);
  }

  // Create a templates directory if needed.
  // Copy over the tpl.php files.
  if (isset($values['template_list'])) {
    $template_list = array_filter($values['template_list']);
    if (!empty($template_list)) {
      $template_directory = $new_dirname . '/templates';
      file_prepare_directory($template_directory, FILE_CREATE_DIRECTORY);
      foreach ($template_list as $template_path) {
        $file = basename($template_path);         // $file is set to "index.php"
        $dest = $template_directory . '/' . $file;
        $source = BACKDROP_ROOT . '/' . $template_path;
        copy($source, $dest);
      }
    }
  }

  // Create CSS and JS folders.
  if (!empty($values['styles'])) {
    foreach ($values['styles'] as $style) {
      $pathinfo = pathinfo($style);
      $path = $new_dirname . '/' . $pathinfo['dirname'];
      file_prepare_directory($path, FILE_CREATE_DIRECTORY);
      file_put_contents($new_dirname . '/' . $style, '');
    }
  }
  if (!empty($values['scripts'])) {
    foreach ($values['scripts'] as $script) {
      $pathinfo = pathinfo($script);
      $path = $new_dirname . '/' . $pathinfo['dirname'];
      file_prepare_directory($path, FILE_CREATE_DIRECTORY);
      file_put_contents($new_dirname . '/' . $script, '');
    }
  }
  
  // Modify the template.php code.
  if (!empty($values['copy_template_php'])) {
    $template_php_content = "<?php\n";
    $template_php_content .= "/**\n";
    $template_php_content .= " * @file\n";
    $template_php_content .= " * " . $values['name'] . " preprocess functions and theme function overrides.\n";
    $template_php_content .= " */\n";

    file_put_contents($new_dirname . '/template.php', $template_php_content);
  }

  // Build the info file.
  $themes = system_rebuild_theme_data();
  $values['theme_name'] = $theme_name;
  $info_file_array = project_maker_build_info_file_array($themes, $values);

  $info_file = project_maker_build_info_file($info_file_array);
  $info_file_path = $new_dirname . '/' . $values['subtheme_name'] . '.info';
  file_put_contents($info_file_path, $info_file);

  return TRUE;

}

/**
 * Converts a file.
 *
 * @param string $filename
 *   The new name of the file to convert.
 */
function project_maker_convert_file($filename, $form_state) {
  if (!file_exists($filename)) {
    return FALSE;
  }

  $extension = pathinfo($filename, PATHINFO_EXTENSION);

  // Read the file and copy the contents.
  $cur = file_get_contents($filename);
  $new = $cur;

  if ($extension != 'js') {
    // String replacement of the base theme human readable name.
    $theme_full_name = $form_state['themes'][$form_state['theme_name']]->info['name'];
    $new = str_replace($theme_full_name, $form_state['values']['name'], $new);
    // String replacement of the base theme machine name.
    $new = str_replace($form_state['theme_name'], $form_state['values']['subtheme_name'], $new);
  }

  // Write the new file.
  if ($new != $cur) {
    if (file_put_contents($filename, $new) === FALSE) {
      return FALSE;
    }
    return TRUE;
  }
}

/**
 * Recursively copy a directory.
 *
 * @param array $item
 *   Array of a directory containing the files to convert.
 */
function project_maker_copy_dir($item) {
  $dirname = $item['old_dir'];
  $new_dirname = $item['new_dir'];

  // Create an output directory we can write to.
  if (!is_dir($new_dirname)) {
    mkdir($new_dirname);
    chmod($new_dirname, 0757);
  }
  else {
    backdrop_set_message(t('Unable to copy directory.'), 'error');
  }

  static $ignore = array(/*'.', '..', '.bzr', '.git', '.svn',*/ 'CVS');

  // Loop on files.
  $filenames = scandir($dirname . '/');
  foreach ($filenames as $filename) {
    if (is_dir($dirname . '/' . $filename)) {

      if (substr(basename($filename), 0, 1) == '.' || in_array(basename($filename), $ignore)) {
        // Ignore all hidden directories and CVS directory.
        continue;
      }

      $new_item = array(
        'old_dir' => $dirname . '/' . $filename,
        'new_dir' => $new_dirname . '/' . $filename,
      );
      project_maker_copy_dir($new_item);
    }
    elseif (!is_dir($dirname . '/' . $filename)) {
      copy($dirname . '/' . $filename, $new_dirname . '/' . $filename);
      project_maker_convert_file($new_dirname . '/' . $filename);
    }
  }
}

/**
 * Build an info file content structure array.
 */
function project_maker_build_info_file_array($values) {
  if ($values['type'] == 'subtheme') {
    $themes = system_rebuild_theme_data();
    $theme_name = $values['theme_name'];
    $data = $themes[$theme_name]->info;
    $description = t('Subtheme of ') . $data['name'];
  }
  elseif ($values['type'] == 'theme') {
    $description = t('Description');
  }
  elseif ($values['type'] == 'module') {
    $description = t('Description');
  }
  if ($values['type'] == 'layout') {
    $description = t('Description');
  }
  $info_file_array['name'] = $values['name'];
  $info_file_array['description'] = $description;
  $info_file_array['type'] = $values['type'];
  $info_file_array['backdrop'] = '1.x';
  if ($values['type'] == 'subtheme') {
    $info_file_array['base theme'] = $theme_name;
  }
  $info_file_array['newline1'] = 'newline';

  if (!empty($values['copy_color'])) {
    $values['styles'][] = 'css/colors.css';
  }
  if (!empty($values['styles'])) {
    $info_file_array['stylesheets'] = array('all' => backdrop_map_assoc($values['styles']));
  }
  $info_file_array['newline2'] = 'newline';

  if (!empty($values['scripts'])) {
    $info_file_array['scripts'] = $values['scripts'];
  }
  $info_file_array['newline3'] = 'newline';

  if (empty($values['copy_settings']) && !empty($values['copy_color'])) {
    $info_file_array['settings']['color'] = 'true';
  }

  backdrop_alter('project_maker_build_info_file', $info_file_array);

  return $info_file_array;
}

/**
 * Build an info file content structure.
 */
function project_maker_build_info_file($info_file_array) {
  $content = "";
  foreach ($info_file_array as $key => $elem) {
    if (is_array($elem)) { 
      foreach ($elem as $subkey => $data) { 
        if (is_array($data)) { 
          foreach ($data as $subsubkey => $subdata) {
            $rendered_key = is_numeric($subkey) ? '' : $subkey;
            $content .= $key ."[" . $rendered_key . "][] = " . project_maker_bool_to_string($data[$subsubkey]) . "\n";
          }
        }
        else {
          $rendered_key = is_numeric($subkey) ? '' : $subkey;
          $content .= $key ."[" . $rendered_key . "] = " . project_maker_bool_to_string($elem[$subkey]) . "\n";
        }
      } 
    } 
    elseif ($elem == "newline") {
      $content .= "\n";
    }
    elseif ($elem == "") {
    }
    elseif ($elem == "newline") {
      $content .= "\n";
    }
    else {
      $content .= $key . " = " . project_maker_bool_to_string($elem) . "\n";
    }      
  }
  return $content;
}

/**
 * Returns string instead of bool.
 */
function project_maker_bool_to_string($value) {
  return is_bool($value) ? (TRUE ? "true" : "false") : $value;
}

/**
 * Implements hook_system_theme_page_alter().
 */
function project_maker_system_themes_page_alter(&$theme_groups) {
  if (user_access('administer project maker')) {
    $all_currently_available_themes = array_keys(list_themes());

    foreach ($theme_groups as $group => $members) {
      if (!empty($group)) {
        foreach ($members as $key => $theme) {
          if (in_array($theme->name, $all_currently_available_themes)) {
            $theme_groups[$group][$key]->operations[] = array(
              'title' => t('Create subtheme'),
              'href' => 'admin/config/development/devel-project maker/' . $theme->name,
              'attributes' => array('title' => t('Create subtheme of @theme', array('@theme' => $theme->info['name']))),
            );
          }
        }
      }
    }
  }
}
